spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/esjadmin?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    # 初始连接数
    initial-size: 5
    # 最大连接池数量
    max-active: 50
    # 最小连接池数量
    min-idle: 10
    # 连接等待超时时间
    max-wait: 10000

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000   #连接超时时间
    jedis:
      pool:
        max-wait: 30000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制)
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
#    root: debug
    com.ershijin: debug


#是否允许生成代码，生产环境设置为false
generator:
  enabled: false

#如果生产环境要开启swagger，需要配置请求地址
#springfox:
#  documentation:
#    swagger:
#      v2:
#        host: # 接口域名或外网ip

#是否开启 swagger-ui
swagger:
  enabled: false

