server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 隔离级别为读写提交
    default-transaction-isolation: 2
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    format:
      date: yyyy-MM-dd HH:mm:ss

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ershijin.model
  global-config:
    db-config:
      id-type: auto #主键策略，数据库自增
  #      update-strategy: default
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    lazy-loading-enabled: true

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50


# 是否本地解析IP地区
ip:
  local-parsing: true

# 登录相关配置
login:
  # 登录缓存
  cache-enable: true
  #  是否限制单用户登录
  single: false
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间单位秒
    expiration: 120
    #  验证码高度
    width: 111
    #  验证码宽度
    heigth: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

#token 配置
token:
  header: Authorization
  # 令牌前缀
  token-start-with: token
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: RGVwOFNndkxOalBNT1ZSeTVVaG5ETU4wMDBtd085MUtGazEwZ2FnMDIxd0t2OWZrOGtFc0tvRGtFcGR2cUZra2JlMGhjbWdORlpLODdaVmRxSkxnMXpZZg==
  # 令牌过期时间 此处单位/秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: authcode-
  # token 续期检查时间范围（默认30分钟，单位秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800
  # 续期时间范围，默认1小时，单位秒
  renew: 3600
